parameters:
  - name: repoUrl
    type: string
    default: 'https://github.com/suprise079/SafeSpeedFront_End.git' # Update this with the actual repository URL

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CloneAndBuild
    displayName: 'Clone Repository and Build React Application'
    jobs:
      - job: CloneAndBuildJob
        steps:
          - script: |
              echo "Cloning repository from ${{ parameters.repoUrl }}"
              git clone ${{ parameters.repoUrl }} repo
              cd repo
              echo "Installing dependencies"
              npm install
              echo "Building React application"
              npm run build
            displayName: 'Clone repository and build React application'

  - stage: DockerBuildAndPush
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: DockerJob
        steps:
          - script: |
              echo "Logging in to Docker Hub"
              docker login --username your-username --password your-password
            displayName: 'Docker Login'
          
          - script: |
              echo "Building Docker image"
              docker build -t your-dockerhub-username/your-image-name:latest .
            displayName: 'Build Docker Image'

          - script: |
              echo "Pushing Docker image to Docker Hub"
              docker push your-dockerhub-username/your-image-name:latest
            displayName: 'Push Docker Image to Docker Hub'

          - script: |
              echo "Docker image pushed successfully."
            displayName: 'Echo Success'

  - stage: DockerRun
    displayName: 'Install Docker and Run Container'
    jobs:
      - job: DockerJob
        steps:
          - script: |
              echo "Running Docker Container"
              docker login --username your-username --password your-password
              docker run -d -p 3000:3000 your-dockerhub-username/your-image-name:latest
            displayName: 'Running Docker Container'
